title: Mobility Toolbox
description: A Open Source Matlab toolbox for mobility generation and simulation data.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
version: 0.0.1
google_analytics: true 
github: {
      is_project_page: true,
      repository_name: mobilitytoolbox,
      owner_url: github.com/imperiumzigna,
      owner_name: Igor Amorim Silva,
      repository_url: "https://github.com/openrsct/mobilitytoolbox",
      zip_url: "https://github.com/openrsct/mobilitytoolbox/archive/v0.0.1.zip",
      tar_url: "https://github.com/openrsct/mobilitytoolbox/archive/v0.0.1.tar.gz"
    }
 
